apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pythonapp
  name: pythonapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pythonapp
  template:
    metadata:
      labels:
        app: pythonapp
    spec:
      containers:
      - image: 09512/pythonapptest:v2
        name: pythonapptest
        ports:
        - containerPort: 5000
